### ISSUE TITLE
Panel heater cumulative energy reported as zero (2.2.85)

### ISSUE THREAD

**Issue by n808** [NamronAS/Namron_Homey#154] opened 2023-12-08 13:47 UTC
Try to and fix an issue with missing energy and power updates for two days, I upgraded to 2.2.85 (test). Current consumption (power) appears to work again, but both heaters now report zero cumulative energy, the most important statistic to keep track of for cost keeping purposes.  Due to the negative jump from the previous cumulative energy, the cost for both heaters is now a large negative number, completely messing up my energy cost record keeping for the house. 

App version 2.2.85 (test)
Manufacturer ID: NAMRON AS
Product ID: 5401393
Firmware: 6.9.1.0_r4
Homey Pro 2023

Diagnostics report: 70b83c8a-8023-4d11-aa7c-6213966e507f

**Comment by prj84** [comment] 2023-12-11 11:32
We have submitted a error report to manufactorer to fix this

**Comment by prj84** [comment] 2023-12-18 08:18
Hi!
Please try with latest update in test and see if the problem is still there. I have tested with 3 different units and now works :-)
https://homey.app/no-no/app/net.filllip-namron/Namron/test/

**Comment by klillevo** [comment] 2023-12-19 09:14
Okay, this appears fixed with test version. Homey rebooted last night, and one of the heaters appears to have stopped updating energy, but everything else works. If there are no changes in Energy the next 24 hours, I will figure out which open issue correspond to the problem, or file a new issue.

**Comment by klillevo** [comment] 2023-12-19 11:00
This issue can be closed - I would do so, but can't seem to find that option. Thanks for fixing this issue so quickly!

**Comment by prj84** [comment] 2023-12-20 11:30
Close as fixed :-)

**Closed by prj84** 2023-12-20 11:30 UTC
Labels: bug
