### ISSUE TITLE
Namron Panel oven zigbee unstable, Homey Pro 2023

### ISSUE THREAD

**Issue by joakimroer** [NamronAS/Namron_Homey#76] opened 2023-04-05 09:38 UTC
Hi
I have 5 Namron zigbee panel oven that are very unstable to my new Homey Pro 2023.
They won't always follow the flows. They don't update energy use and if I adjust the temperature manually they won't always follow.
The time and date also show wrong even the "sync time" button is turned ON.
Tried to reconnect but they work in some hours and falls out again.

**Comment by joakimroer** [comment] 2023-04-11 08:27
A lot of days out of connection :(
Please fix this if you want to have zigbee panel oven in your line up. All other Namron zigbee devices are doing well.


![Screenshot_20230411_102021_Homey](https://user-images.githubusercontent.com/84479112/231101482-4489ca8e-465f-478f-a513-e59430bd1444.jpg)
![Screenshot_20230411_102036_Homey](https://user-images.githubusercontent.com/84479112/231101489-d726e0e7-ce38-40ff-b2a9-b7d2cf56b8c7.jpg)
![Screenshot_20230411_102106_Homey](https://user-images.githubusercontent.com/84479112/231101492-253a1b5e-d150-49cf-8012-c4c371aea084.jpg)
![Screenshot_20230411_101926_Homey](https://user-images.githubusercontent.com/84479112/231101496-d842105d-fff6-4bb2-a399-980651fcda4a.jpg)

**Comment by prj84** [comment] 2023-04-18 06:23
Hi! We are working on tuning the app for the new Homey Pro. Access to the Homey Pro 2023 is still a bit limited, so not all our developers have access to it at this point. But we are slowly getting there. There is small changes in behavior from Homey 2019 to 2023 because all code has been rewritten for it.

**Comment by prj84** [comment] 2023-07-31 09:54
@joakimroer - What is latest experience? Homey has made a lot off updates on the Zigbee core, and connectivity issue is one of the problems they have marked as fixed :-)

**Comment by joakimroer** [comment] 2023-08-08 11:39
Koblet fra alle ovnene for 1 uke siden og koblet til igjen.
Har laget en flow som øker temp til over romtemp og står at ovnene ikke har rapportert effekt på 7 dager.
Så da har de ramlet ut igjen.
________________________________
Fra: Pål Hefre ***@***.***>
Sendt: mandag 31. juli 2023 11:54
Til: NamronAS/Namron_Homey ***@***.***>
Kopi: joakimroer ***@***.***>; Mention ***@***.***>
Emne: Re: [NamronAS/Namron_Homey] Namron Panel oven zigbee unstable, Homey Pro 2023 (Issue #76)


@joakimroer<https://github.com/joakimroer> - What is latest experience? Homey has made a lot off updates on the Zigbee core, and connectivity issue is one of the problems they have marked as fixed :-)

**Comment by konaess** [comment] 2023-10-19 11:36
Hi. I bought a namron panel oven. It is possible to edit set point and change advanced settings. The oven is not reporting effect or consumption to homey. 
![image_123650291](https://github.com/NamronAS/Namron_Homey/assets/148451211/32ac866d-6b7d-4106-96c6-f5fd51f23127)
Any fix for this issue?

**Comment by tdrevvatne** [comment] 2023-11-21 15:56
I have 5x namron panel ovens - trying to control through flowns in Homey 2023.
I've given up my first strategy, trying to control thermostat on the ovens from vThermo - but ovens continues to live their ovn lives......
Second strategy is to turn off the ovens when vTherm goes off state - turn them on when wTherm goes on state + adjust ovens termostat to vTherm temp + 5.
This seems to work - but it's a strange workaround
Any update?
- Namron app?
- Namron ovens firmware?

**Comment by prj84** [comment] 2023-12-22 11:25
> I have 5x namron panel ovens - trying to control through flowns in Homey 2023. I've given up my first strategy, trying to control thermostat on the ovens from vThermo - but ovens continues to live their ovn lives...... Second strategy is to turn off the ovens when vTherm goes off state - turn them on when wTherm goes on state + adjust ovens termostat to vTherm temp + 5. This seems to work - but it's a strange workaround Any update?
> 
> * Namron app?
> * Namron ovens firmware?

Hi! What batch number is there on the panel heater? it is marked on the heater it self. Should be 04/22 or 09/22.

**Comment by tobiassen** [comment] 2024-01-11 20:33
I have the exact same issue, 5 panel ovens none of them have reported effect since 2 - 4 days.
Any update on this issue?
All of them reported effect as expected the first 14 days, then nothing, and I'm unable to get them to report effect at all now.

**Comment by prj84** [comment] 2024-01-16 12:32
Please find attached OTA files, it is for use with Batch 04/22 and will not work with 09/22.
[Zigbee Panel Heater v1 OTA to v2.zip](https://github.com/NamronAS/Namron_Homey/files/13949865/Zigbee.Panel.Heater.v1.OTA.to.v2.zip)

**Comment by prj84** [comment] 2024-01-17 08:59
Homey do not support OTA upgrade as of now. We are looking into what can be done. I will also inform developer that some users still do not see the effect in the app. This is not seen on other platforms and all testusers report that the issue is resolved with the 09/22.

**Comment by R-nny** [comment] 2024-01-23 11:40
@prj84 I have several namron ovens and temp/humidity sensors, all seems to have this issue. 
The temp sensors sometimes needs to be repaired to work again. 
They were all bought between november and january.

Could you confirm that the mentioned issues will be fixed if i upgrade the firmware?
The sensors are on v2.01 and the ovens are on 6.10.3.0

Just want to mention, everytime i send commands to the oven, e.g. turn it on/off or change temperature, it is taken immidiately into effect, also some of the sensors with this issue is just next to the homey, so there shouldnt be any signalling issues.
And shelly devices works without a hitch.

**Closed** 2024-09-30 13:17 UTC
Labels: bug
