### ISSUE TITLE
Missing power metering for 1402756 

### ISSUE THREAD

**Issue by selindoe** [NamronAS/Namron_Homey#93] opened 2023-07-05 09:03 UTC
I see from Homey App Change Log that Power metering support was removed for 1402756 in March 2023.
Is there any plans to reinclude the support in the future? 

> 2.2.646. mar. 2023
> Temp remove Power metering and measuring from 1402756 to resolve cloud issue.

From https://homey.app/no-no/app/net.filllip-namron/Namron/

**Comment by prj84** [comment] 2023-07-31 09:36
Hi! Our supplier is working on the issue. There is some features missing in the z-wave integration that the unit needs to work properly. We will reintroduce if the issue is resolved by Homey

**Closed by prj84** 2023-07-31 09:36 UTC
